weights: runs/train/exp5/weights/best.pt
cfg: models/yolov5n.yaml
data: data/laborotomato.yaml
hyp: data/hyps/hyp.scratch-low.yaml
epochs: 384
batch_size: 128
imgsz: 640
rect: false
resume: false
nosave: false
noval: true
noautoanchor: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: true
sync_bn: false
workers: 8
project: runs/train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: runs/train/exp11
